FROM alpine:latest
CMD echo "Hello World^^"

LABEL org.opencontainers.image.source=https://github.com/hlchiu/Github-Examples
LABEL org.opencontainers.image.description="My container image"
LABEL org.opencontainers.image.licenses=MIT
